### ISSUE TITLE
如何随机订阅消息

### ISSUE THREAD

**Issue by anjoy8** [wmowm/InitQ#1]
问题描述：  
1、我同时定义了两个订阅者RedisSubscribe和RedisSubscribe2；
2、然后注册进去
```
  services.AddInitQ(m =>
  {
      m.SuspendTime = 1000;
      m.ConnectionString = "127.0.0.1:6379";
      m.ListSubscribe = new List<IRedisSubscribe>() { new RedisSubscribe2(), new RedisSubscribe() };
      m.ShowLog = false;
  });

```

问题：
现在的结果是，一直第一个注册的订阅者消费消息，如上文的RedisSubscribe2.
![图片](https://user-images.githubusercontent.com/28941816/92061374-af638b00-edc8-11ea-97e5-4d4977773c63.png)

我如何让他们两个分担呢？

**Comment by wmowm** [comment]
> 问题描述：
> 1，我同时定义了两个订阅者RedisSubscribe和RedisSubscribe2；
> 2，然后注册进去
> 
> ```
>   services.AddInitQ(m =>
>   {
>       m.SuspendTime = 1000;
>       m.ConnectionString = "127.0.0.1:6379";
>       m.ListSubscribe = new List<IRedisSubscribe>() { new RedisSubscribe2(), new RedisSubscribe() };
>       m.ShowLog = false;
>   });
> ```
> 
> 问题：
> 现在的结果是，一直第一个注册的订阅者消费消息，如上文的RedisSubscribe2。
> ![图片](https://user-images.githubusercontent.com/28941816/92061374-af638b00-edc8-11ea-97e5-4d4977773c63.png)
> 
> 我如何让他们两个分担呢？

这个问题与.net core的依赖注入有关,当两个实例都实现一个接口,从仓库获取实例的时候默认只会获取一个,定义一个实现即可,如果想实现交叉打印,可以让两个方法订阅一个队列
