### ISSUE TITLE
延迟队列 跟普通队列放一起 平常测试是有 很高的机率不执行

### ISSUE THREAD

**Issue by miaobei5555** [wmowm/InitQ#11]
延迟队列 跟普通队列放一起 平常测试是有 很高的机率不执行 非得重启进程才会执行 不知道 是什么原因?

**Comment by wmowm** [comment]
提供一下使用InitQ的版本,以及示例demo

**Comment by miaobei5555** [comment]
使用的是最新版本的 demo 也看不出来什么 关键不是每次都触发 换成rabbitmq 就正常

**Comment by wmowm** [comment]
延迟队列跟普通队列是分开的,不能共用一个key

**Comment by miaobei5555** [comment]
哦哦 难怪啊!

**Comment by gou9ping** [comment]
IIS部署的普通队列不执行，必须要重启进程才行
