### ISSUE TITLE
升级到1.0.0.19不执行任务了。

### ISSUE THREAD

**Issue by jianweie** [wmowm/InitQ#20]
升级到1.0.0.19不执行任务了。我看了下1.0.0.18升级到1.0.0.19的合并记录，增加了DbIndex，是不是现在要单独设置redis的dafaultdatabase了？默认不能从ConnectionString取了?

**Comment by wmowm** [comment]
默认情况下,一般不在ConnectionString里指定DbIndex,数据默认存储在db0,如果你之前的ConnectionString有指定过DbIndex,在使用1.0.0.19的时候需要在配置文件里也指定相同的DbIndex,建议链接里不要增加额外的配置信息,这些配置信息由配置文件统一管理
