### ISSUE TITLE
不支持哨兵模式

### ISSUE THREAD

**Issue by heyz** [wmowm/InitQ#6]
如题，目前通过字符串配置单机和集群模式正常工作，单哨兵不行。
如果引用InitQ项目的本身已经单例注入了ConnectionMultiplexer，是否可以在项目里面自己引用ConnectionMultiplexer对象，来避免二次初始化，提升性能？

**Comment by wmowm** [comment]
如果您希望使用自己构建的connectionMultiplexer对象,来创建redis实例,可以在RedisCacheService里新增构造函数来实现,本次提议将会在下个版本更新
