### ISSUE TITLE
Fail

### ISSUE THREAD

**Issue by boogaloo-jw** [wmowm/InitQ#9]
Follow the instructions, message queuing, subscriber failed to subscribe...

**Comment by wmowm** [comment]
请提供相应的示例代码，也可以直接线下与我联系交流，github不会经常关注

**Comment by boogaloo-jw** [comment]
> 请提供相应的示例代码，也可以直接线下与我联系交流，github不会经常关注
感谢回复！问题已解决！是我自己的问题

**Comment by boogaloo-jw** [comment]
简单好用！
